**Objetivo:** repetir con un dataset diferente las operaciones vistas con Pingüinos: explorar, seleccionar, filtrar, agrupar, limpiar, transformar y exportar.

**Importante:** usa el material de referencia, documentación y, si lo deseas, un asistente de IA. Debes **entender y comprobar** el código. Las celdas están intencionadamente sin resolver.

## Preparación
Este archivo usa una copia didáctica del dataset Iris con **8 celdas vacías introducidas para practicar limpieza**. Son 150 flores, tres especies y cuatro mediciones. Los datos originales se guardan en `iris_original.csv` para comparar.

Coloca este notebook en la misma carpeta que los archivos CSV. Si aparece `FileNotFoundError`, revisa la carpeta abierta en VS Code.

**Comprobación esperada:** `(150, 5)`.

**Referencia de columnas:** `sepal_length_cm`, `sepal_width_cm`, `petal_length_cm`, `petal_width_cm`, `species`. Las medidas están expresadas en centímetros.

## Ejercicio 1. Explorar el dataset

a) Muestra las primeras cinco filas. b) Identifica las dimensiones. c) Consulta los tipos de columna y sus valores no nulos. d) Encuentra cuáles especies aparecen en la columna `species`.

**Pista:** Recuerda `head`, `shape`, `info` y `unique`. Debes encontrar **3 especies**.

In [ ]:
import pandas as pd

# Cargar el dataset
df = pd.read_csv("iris_con_faltantes.csv")

print("a) Primeras cinco filas")
display(df.head(5))

print("b) dimensiones (filas, columnas)")
print("Dimensiones:", df.shape)

print("c) Tipos de columna y sus valores no nulos")
df.info()

print("d) Especies")
print("Especies:", df["species"].unique())

a) Primeras cinco filas

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             NaN              1.4             0.2  setosa

b) dimensiones (filas, columnas)
Dimensiones: (150, 5)
c) Tipos de columna y sus valores no nulos
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sepal_length_cm  150 non-null    float64
 1   sepal_width_cm   145 non-null    float64
 2   petal_length_cm  150 non-null    float64
 3   petal_width_cm   147 non-null    float64
 4   species          150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB
d) Especies
Especies: <StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

## Ejercicio 2. Seleccionar columnas y posiciones

a) Crea una tabla que contenga solo `species` y `petal_length_cm`. b) Muestra **las cinco primeras filas y las dos primeras columnas** mediante posiciones, no nombres.

**Pista:** Usa una lista de columnas para (a) y `iloc` para (b). El final de un slice no se incluye.

In [11]:
print("a) Tabla 'species' y 'petal_length_cm'")
tabla_columnas = df[["species", "petal_length_cm"]]
display(tabla_columnas.head(5))

print("b) 5 primeras filas y 2 primeras columnas por posición")
display(df.iloc[0:5, 0:2])

a) Tabla 'species' y 'petal_length_cm'

  species  petal_length_cm
0  setosa              1.4
1  setosa              1.4
2  setosa              1.3
3  setosa              1.5
4  setosa              1.4

b) 5 primeras filas y 2 primeras columnas por posición

   sepal_length_cm  sepal_width_cm
0              5.1             3.5
1              4.9             3.0
2              4.7             3.2
3              4.6             3.1
4              5.0             NaN

## Ejercicio 3. Filtrar con una o dos condiciones

a) Selecciona solamente flores de la especie `setosa`. b) Selecciona flores de `virginica` cuyo `petal_length_cm` sea **mayor que 5.5**. c) Muestra cuántas filas tiene cada resultado.

**Pista:** Utiliza una máscara de comparación y `&`; cada condición debe ir entre paréntesis.

In [ ]:
print("a) Flores unicamente de la especie 'setosa'")

mascara_setosa = df["species"] == "setosa"
setosa_df = df.loc[mascara_setosa]

print("b) Flores de 'virginica' con petal_length_cm mayor a 5.5")
mascara_virginica = (df["species"] == "virginica") & (df["petal_length_cm"] > 5.5)
virginica_grandes = df.loc[mascara_virginica]

print("c) Mostrar cuántas filas tiene cada resultado")
print("Cantidad de flores 'setosa':", len(setosa_df))
print("Cantidad de flores 'virginica' con pétalo > 5.5 cm:", len(virginica_grandes))

print("Visualizacion de muestra para comprobar")
display(setosa_df.head(3))
display(virginica_grandes.head(3))

a) Flores unicamente de la especie 'setosa'
b) Flores de 'virginica' con petal_length_cm mayor a 5.5
c) Mostrar cuántas filas tiene cada resultado
Cantidad de flores 'setosa': 50
Cantidad de flores 'virginica' con pétalo > 5.5 cm: 25
 Visualización de muestra para comprobar

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
100,6.3,3.3,6.0,NaN,virginica
102,7.1,3.0,5.9,2.1,virginica
103,6.3,2.9,5.6,1.8,virginica

## Ejercicio 4. Contar y agrupar por especie

a) Cuenta cuántas flores hay de cada especie. b) Calcula el **promedio de `petal_length_cm` para cada especie**. c) Identifica cuál tiene el promedio mayor.

**Pista:** Busca `value_counts`, `groupby` y `mean`. La columna `petal_length_cm` no contiene faltantes en esta copia.

In [17]:
print("a)Conteo de flores por especie:")
print(df["species"].value_counts())


promedios_petalo = df.groupby("species")["petal_length_cm"].mean()
print("b)Promedio de longitud de pétalo (cm) por especie:")
print(promedios_petalo)


especie_mayor = promedios_petalo.idxmax()
valor_mayor = promedios_petalo.max()

print(f"C)La especie con el promedio mayor es '{especie_mayor}' con {valor_mayor} cm.")

a)Conteo de flores por especie:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64
b)Promedio de longitud de pétalo (cm) por especie:
species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length_cm, dtype: float64
C)La especie con el promedio mayor es 'virginica' con 5.5520000000000005 cm.

## Ejercicio 5. Limpiar valores faltantes y quitar columnas

a) Cuenta cuántos valores faltan por columna. b) Crea **una copia** sin las filas que tengan valores vacíos y cuenta cuántas quedan. c) Crea otra copia donde rellenes únicamente los faltantes de `sepal_width_cm` con su mediana. d) Crea una tercera copia sin la columna `petal_width_cm`. **No modifiques `iris` directamente.**

**Pista:** Recuerda `isna().sum()`, `dropna()`, `fillna()`, `median()` y `drop(columns=[...])`. Esperamos **142 filas completas** antes de rellenar.

In [19]:
print("a) Faltantes por columna:")
print(df.isna().sum())

sin_vacios = df.dropna().copy()
print("b) Filas restantes sin valores vacíos:", len(sin_vacios))

copia_rellenada = df.copy()
mediana_sepal_width = copia_rellenada["sepal_width_cm"].median()
copia_rellenada["sepal_width_cm"] = copia_rellenada["sepal_width_cm"].fillna(mediana_sepal_width)
print("c) Faltantes en 'sepal_width_cm':", copia_rellenada["sepal_width_cm"].isna().sum())

# d) Copia sin la columna 'petal_width_cm'
copia_sin_columna = df.drop(columns=["petal_width_cm"]).copy()
print("d) Columnas restantes tras drop:", list(copia_sin_columna.columns))
print("Dimensiones de la tabla sin la columna:", copia_sin_columna.shape)

a) Faltantes por columna:
sepal_length_cm    0
sepal_width_cm     5
petal_length_cm    0
petal_width_cm     3
species            0
dtype: int64
b) Filas restantes sin valores vacíos: 142
c) Faltantes en 'sepal_width_cm': 0
d) Columnas restantes tras drop: ['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'species']
Dimensiones de la tabla sin la columna: (150, 4)

## Ejercicio 6. Transformar columnas

a) Crea en una copia una nueva columna `petal_length_mm` convirtiendo centímetros a milímetros. b) Crea otra columna `species_codigo` asignando `S`, `V` y `G` a las tres especies. c) Comprueba cinco filas.

**Pista:** Para la conversión basta una operación sobre toda la columna; para códigos puedes usar `.map()` con un diccionario. Si quieres, prueba también `.apply(lambda ...)`.

In [20]:
# copia independiente para trabajar las transformaciones
copia_transformada = df.copy()

# a) Nueva columna petal_length_mm convirtiendo cm a mm (* 10)
copia_transformada["petal_length_mm"] = copia_transformada["petal_length_cm"] * 10


# b) Nueva columna species_codigo asignando 'S', 'V' y 'G'
mapeo_especies = {
    "setosa": "S",
    "versicolor": "V",
    "virginica": "G"
}
copia_transformada["species_codigo"] = copia_transformada["species"].map(mapeo_especies)

# c) Comprobar cinco filas con las columnas clave
columnas_revision = ["species", "species_codigo", "petal_length_cm", "petal_length_mm"]
display(copia_transformada[columnas_revision].head(5))

  species species_codigo  petal_length_cm  petal_length_mm
0  setosa              S              1.4             14.0
1  setosa              S              1.4             14.0
2  setosa              S              1.3             13.0
3  setosa              S              1.5             15.0
4  setosa              S              1.4             14.0

## Ejercicio 7. Exportar el resultado

a) Guarda el DataFrame transformado del ejercicio 6 en `iris_procesado.csv`, **sin guardar la columna de índice**. b) Vuelve a leer el CSV con Pandas y comprueba que conserva 150 filas y las nuevas columnas.

**Pista:** Usa `to_csv` con `index=False` y después `read_csv`.

In [21]:
# a) Exportar el DataFrame transformado a CSV sin incluir el índice
copia_transformada.to_csv("iris_procesado.csv", index=False)

# b) Volver a leer el archivo exportado y comprobar dimensiones y columnas
df_recargado = pd.read_csv("iris_procesado.csv")

print("Dimensiones (filas, columnas):", df_recargado.shape)
print("Columnas en el archivo:", list(df_recargado.columns))

# Visualizar las primeras filas para confirmar los datos
display(df_recargado.head(3))

Dimensiones (filas, columnas): (150, 7)
Columnas en el archivo: ['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'petal_width_cm', 'species', 'petal_length_mm', 'species_codigo']

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,petal_length_mm,species_codigo
0,5.1,3.5,1.4,0.2,setosa,14.0,S
1,4.9,3.0,1.4,0.2,setosa,14.0,S
2,4.7,3.2,1.3,0.2,setosa,13.0,S

## Ejercicio 8. Unir filas con `concat`

a) Construye dos DataFrames: primeras 50 filas y siguientes 50 filas de `iris`. b) Únelos verticalmente y comprueba el número total de filas.

**Pista:** Combina `iloc` y `pd.concat`; prueba `ignore_index=True`.

In [22]:
# a) Construir dos DataFrames: primeras 50 filas y siguientes 50 filas
parte_1 = df.iloc[0:50]
parte_2 = df.iloc[50:100]

print("Filas de la parte 1:", len(parte_1))
print("Filas de la parte 2:", len(parte_2))

# b) Unir verticalmente con pd.concat y reiniciar el índice
unidos = pd.concat([parte_1, parte_2], ignore_index=True)

# Comprobar el número total de filas y dimensiones
print("\nFilas combinadas:", unidos.shape[0])
print("Dimensiones totales:", unidos.shape)

# Comprobar las primeras y últimas filas del DataFrame resultante
display(unidos.head(3))
display(unidos.tail(3))

Filas de la parte 1: 50
Filas de la parte 2: 50

Filas combinadas: 100
Dimensiones totales: (100, 5)

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
97,6.2,2.9,4.3,1.3,versicolor
98,5.1,2.5,3.0,1.1,versicolor
99,5.7,2.8,4.1,1.3,versicolor

## Ejercicio 9. Relacionar tablas con `merge`
Crea una tabla pequeña con las columnas `species` y `codigo`: setosa→S, versicolor→V y virginica→G. Une esta tabla con `iris` mediante la especie. Verifica que aparecen 150 filas y una columna adicional. Los códigos son solamente etiquetas didácticas.

**Pista:** Puedes construir la tabla auxiliar con `pd.DataFrame({...})` y hacer un `merge` por `species`.

In [23]:
# 1 Crear la tabla auxiliar con códigos
codigos_iris = pd.DataFrame({
    "species": ["setosa", "versicolor", "virginica"],
    "codigo": ["S", "V", "G"]
})

print("Tabla auxiliar:")
print(codigos_iris)

# 2 Relacionar la tabla auxiliar con iris mediante la columna clave común
iris_combinado = df.merge(codigos_iris, on="species", how="left")

# 3 Comprobar dimensiones y columnas resultantes
print("Dimensiones originales de df:", df.shape)
print("Dimensiones tras merge:", iris_combinado.shape)

# 4. Visualizar las primeras filas para confirmar la nueva columna
display(iris_combinado[["species", "codigo", "petal_length_cm", "petal_width_cm"]].head(5))

Tabla auxiliar:
      species codigo
0      setosa      S
1  versicolor      V
2   virginica      G
Dimensiones originales de df: (150, 5)
Dimensiones tras merge: (150, 6)

  species codigo  petal_length_cm  petal_width_cm
0  setosa      S              1.4             0.2
1  setosa      S              1.4             0.2
2  setosa      S              1.3             0.2
3  setosa      S              1.5             0.2
4  setosa      S              1.4             0.2

## Antes de entregar
**Guarde en un Github creado Público** `git status` → `git add .` → `git commit -m "Practicar consultas y transformaciones con Pandas"`. Evita subir al repositorio archivos de entornos virtuales (`.venv/`).